name: medical_consultation_app
description: "Aplicativo de consultas médicas online"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0

  # Dependency Injection
  get_it: ^8.1.0
  injectable: ^2.3.2

  # Navigation
  go_router: ^16.0.0

  # HTTP Client
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Media & Files
  image_picker: ^1.0.7
  file_picker: ^10.2.1

  # Real-time Communication
  socket_io_client: ^3.1.2

  # Date & Time
  intl: ^0.20.2
  timeago: ^3.6.1

  # Forms & Validation
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0

  # UI Enhancements
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  lottie: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # Utilities
  uuid: ^4.3.3
  permission_handler: ^12.0.1
  url_launcher: ^6.2.4
  package_info_plus: ^8.3.0
  device_info_plus: ^11.5.0
  mask_text_input_formatter: ^2.9.0
  share_plus: ^7.0.0

  # JSON Serialization
  json_annotation: ^4.9.0
  json_serializable: ^6.7.1

  # Charts
  fl_chart: ^1.0.0

  # Notifications
  firebase_messaging: ^16.0.0
  firebase_core: ^4.0.0
  flutter_local_notifications: ^19.4.0
  fluttertoast: ^8.2.12

  # add icons
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  mobx_codegen: ^2.4.0+1
  # Linting
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  android: true
  ios: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/default_doctor.png
    - assets/animations/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700