-- Desabilitar RLS temporariamente
ALTER TABLE IF EXISTS ratings DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS prescriptions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS schedules DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS messages DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS consultations DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS doctor_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS patient_profiles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS users DISABLE ROW LEVEL SECURITY;

-- Apagar tabelas na ordem correta (devido às foreign keys)
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS prescriptions CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS messages CASCADE;
DROP TABLE IF EXISTS consultations CASCADE;
DROP TABLE IF EXISTS doctor_profiles CASCADE;
DROP TABLE IF EXISTS patient_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Apagar ENUMs
DROP TYPE IF EXISTS "UserType" CASCADE;
DROP TYPE IF EXISTS "Gender" CASCADE;
DROP TYPE IF EXISTS "ConsultationStatus" CASCADE;
DROP TYPE IF EXISTS "MessageType" CASCADE;

-- Apagar funções auxiliares
DROP FUNCTION IF EXISTS update_updated_at_column() CASCADE;